### ISSUE TITLE
If you create a PR with ( ) in the title it breaks the process

### ISSUE THREAD

**Issue by fbrodrigorezino** [8BitJonny/gh-get-current-pr#117]
## Subject of the issue
I created a PR with the title:  `fix!: Something (something)`

## Your git environment
It's a closed repo

## Steps to reproduce
Create a PR with `(`or `)` in the title and try to call. I didn't check for other special chars

```
      - name: Information
        run: |
          echo Base PR URL: ${{ steps.PR.outputs.pr_url }}
          echo Based On PR Title: ${{ steps.PR.outputs.pr_title }}
```

## Expected behaviour
Should output the info about the PR

## Actual behaviour
```
Run echo Base PR URL: https://github.com/***/pull/22
/home/runner/work/_temp/547790f0-2141-4ff[8](https://github.com/***o/runs/7837860134?check_suite_focus=true#step:6:9)-b1b6-5d0fdf8883c8.sh: line 2: syntax error near unexpected token `('
Base PR URL: https://github.com/****/pull/22
Error: Process completed with exit code 2.
```

**Comment by 8BitJonny** [comment]
Hey @fbrodrigorezino,
thanks for opening this ticket. I hope you are doing well.

I just had a look into your described issue and you can see my debugging process here #124 (I have yet to find a better way to run and debug the action locally, thats why for now I'm stuck with debugging through pushing to Github)

But you see through the action output [here](https://github.com/8BitJonny/gh-get-current-pr/runs/7876115194?check_suite_focus=true#step:8:48) that in fact even a PR with special characters like `(` or `)` is detected and put into the output variable `${{ steps.pr.outputs.pr_title }}` without a problem.

The problem here is that the bash command cannot handle the content of `${{ steps.pr.outputs.pr_title }}` containing special characters.
So the solution in this case was to wrap the wanted output in strings like this:
```yaml
  - name: Information
     run: |
       echo "Base PR URL: ${{ steps.PR.outputs.pr_url }}"
       echo "Based On PR Title: ${{ steps.PR.outputs.pr_title }}"
```

I hope I could help
